theme: jekyll-theme-hacker
baseurl: ''
# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: ''

github:
  username: github_username             # change to your github username
